module.exports = {
    COMMUNITY_CHAT : "COMMUNITY_CHAT",
    VERIFY_USER : "VERIFY_USER",
    USER_CONNECTED : "USER_CONNECTED",
    USER_DISCONNECTED : "USER_DISCONNECTED",
    MESSAGE_RECIEVED : "MESSAGE_RECIEVED",
    MESSAGE_SENT : "MESSAGE_SENT",
    TYPING : "TYPING",
    LOGOUT : "LOGOUT"  
}